"""Domain data classes.

All types are pure dataclasses — no logic, no imports from other tools modules.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Chunk:
    """A text fragment stored in the knowledge base."""

    id: str
    text: str
    source: str
    similarity: float = 0.0
    from_other_project: bool = False
    chunk_idx: int = 0
    doc_id: str = ""
    project: str = "default"


@dataclass
class Entity:
    """A named concept or identifier extracted from documents."""

    id: str
    name: str
    type: str = "concept"
    project: str = "default"


@dataclass
class Relation:
    """A directed, typed edge between two entities."""

    from_entity: str
    to_entity: str
    relation_type: str
    confidence: float = 0.0
    verified: bool = False
    source_text: str = ""
    target_text: str = ""
    project: str = "default"
    # True when generated by a heuristic / placeholder source (no real evidence).
    # Synthetic relations are persisted with a flag so dashboards can exclude
    # them from "relations_proposed / accepted" totals.
    synthetic: bool = False
    # Per-relation provenance — populated by callers when known so the graph
    # can be audited (which session / tool / time produced the edge). Empty
    # strings mean "unknown" and remain backward compatible with v0.2.x edges.
    session_id: str = ""
    origin_tool: str = ""
    created_at: str = ""
    # Hyper-relational qualifiers (RDF-star style): per-edge key/value metadata.
    # Canonical reserved keys — "valid_from", "valid_to" (ISO-8601 temporal
    # validity), "verifier" (srmkg | vog | manual | gnn), "evidence_chunk_id",
    # "derived_from", "source_doc". A missing map is an empty dict, so legacy
    # v0.2.x edges stay compatible.
    qualifiers: dict[str, str] = field(default_factory=dict)

    @property
    def valid_from(self) -> str:
        """Canonical temporal-start qualifier (empty when unset)."""
        return self.qualifiers.get("valid_from", "")

    @property
    def valid_to(self) -> str:
        """Canonical temporal-end qualifier (empty == still current)."""
        return self.qualifiers.get("valid_to", "")

    @property
    def verifier(self) -> str:
        """Which layer last vouched for this edge (empty when unset)."""
        return self.qualifiers.get("verifier", "")


# Canonical qualifier keys recognised across the graph + federation layers.
CANONICAL_QUALIFIERS: frozenset[str] = frozenset(
    {
        "valid_from",
        "valid_to",
        "verifier",
        "evidence_chunk_id",
        "derived_from",
        "source_doc",
    }
)


def merge_qualifiers(base: dict[str, str], incoming: dict[str, str]) -> dict[str, str]:
    """Collision-safe union of two qualifier maps.

    Used when the same ``(from, relation_type, to)`` edge is re-observed so
    accumulated provenance is preserved instead of overwritten. *incoming*
    wins on per-key conflicts (the newer observation), mirroring the
    "last/highest wins" rule the session CRDT already uses. Empty incoming
    values never clobber an existing non-empty value.
    """
    merged = dict(base or {})
    for key, value in (incoming or {}).items():
        if value not in (None, ""):
            merged[key] = value
    return merged


def _norm_start(value: str) -> str:
    """Normalise a date-only bound to the start-of-day instant."""
    return f"{value}T00:00:00Z" if len(value) == 10 else value


def _norm_end(value: str) -> str:
    """Normalise a date-only bound to the end-of-day instant."""
    return f"{value}T23:59:59Z" if len(value) == 10 else value


def relation_valid_at(qualifiers: dict[str, str], as_of: str) -> bool:
    """True when an edge's temporal-validity window contains *as_of*.

    Compares ISO-8601 strings lexicographically, normalising bare
    ``YYYY-MM-DD`` bounds the way MemPalace's temporal KG does: a date-only
    ``valid_from`` counts from start-of-day, a date-only ``valid_to`` through
    end-of-day. Missing ``valid_from`` == "always started"; missing
    ``valid_to`` == "still current"; an empty *as_of* matches everything.
    """
    if not as_of:
        return True
    point = _norm_start(as_of)
    q = qualifiers or {}
    valid_from = q.get("valid_from", "")
    valid_to = q.get("valid_to", "")
    if valid_from and point < _norm_start(valid_from):
        return False
    if valid_to and point > _norm_end(valid_to):
        return False
    return True
